name: Nepse data auto scrapping

on:
  push:
    branches:
      - main
  schedule:
    - cron: '15 11 * * *' # 11:15 AM UTC
jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 
        uses: actions/checkout@v2

      - name: Python Setup Environment
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      
      - name: Install Dependencies
        run: |
          pip install -r requirements.txt
      
      - name: Install Chrome
        run: |
          wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -
          echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list
          apt-get update
          apt-get install -y google-chrome-stable
      
      - name: scrapping of data script
        run: |
          python3 app.py
      - name: Commit and Push Files
        run: |
          git config --local user.email "bhupinbaral.729@gmail.com"
          git config --local user.name "bhupinbaral25"        
          git add .
          git commit -am "scrapped successfully!"
          git push origin main
