name: Nepse data auto scrapping

on:
  push:
    branches:
      - main
  schedule:
    - cron: '15 11 * * *' # 11:15 AM UTC
jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 
        uses: actions/checkout@v2

      - name: Python Setup Environment
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      
      - name: Install Dependencies
        run: |
          pip install -r requirements.txt
      
      - name: install Chrome Driver
          uses: actions/checkout@v2
          uses: nanasess/setup-chromedriver@v1
          with:
        # Optional: do not specify to match Chrome's version
          chromedriver-version: '88.0.4324.96'
          run:
          export DISPLAY=:99
          chromedriver --url-base=/wd/hub &
          sudo Xvfb -ac :99 -screen 0 1280x1024x24 > /dev/null 2>&1 & # optional

      
      - name: scrapping of data script
        run: |
          python3 app.py
      - name: Commit and Push Files
        run: |
          git config --local user.email "bhupinbaral.729@gmail.com"
          git config --local user.name "bhupinbaral25"        
          git add .
          git commit -am "scrapped successfully!"
          git push origin main
